full_base_version:                # [linux]
  - "1.9.0 eigen_py36hdfca3bf_0"  # [linux]
  - "1.9.0 mkl_py36h2ca6a6a_0"    # [linux]
select_version:                   # [linux]
  - "0.0.2 eigen"                 # [linux]
  - "0.0.3 mkl"                   # [linux]
tflow_variant:                    # [linux]
  - "eigen"                       # [linux]
  - "mkl"                         # [linux]
py_version:                       # [linux]
  - 3.6                           # [linux]
  - 3.6                           # [linux]
zip_keys:                         # [linux]
  - full_base_version             # [linux]
  - select_version                # [linux]
  - tflow_variant                 # [linux]
  - py_version                    # [linux]
