{% set version = "1.9.0" %}

package:
  name: tensorboard
  version: {{ version }}

source:
  fn: tensorflow-{{ version }}.tar.gz                                          # [unix]
  url: https://github.com/tensorflow/tensorboard/archive/{{ version }}.tar.gz  # [unix]
  sha256: 95663d6c3d05243913ce433fa1cc86c64181f46e74b1fd9429e1b9e39ec5e59c     # [unix]

  # Rename this to dummy since we don't want CB to extract it
  fn: tensorboard-{{ version }}-py3-none-any.whl.dummy                                        # [win]
  url: https://pypi.io/packages/py3/t/tensorboard/tensorboard-{{ version }}-py3-none-any.whl  # [win]
  sha256: 42a04637a636e16054b065907c81396b83a9702948ecd14218f19dc5cf85de98                    # [win]

build:
  number: 0
  skip: True  # [not x86_64]
  skip: True  # [win and vc<14]
  # Make sure there is no tensorboard entry point in the tensorflow-{gpu-,}base
  # packages as it conflicts with a file in this package.
  entry_points:
    - tensorboard = tensorboard.main:run_main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    # Not using bazel on Windows due to issue with long paths
    # The package contents are not OS specific anyway
    - bazel >=0.9.0  # [unix]
    - python
    - setuptools
    - pip            # [win]
  run:
    - python
    - werkzeug >=0.11.10
    - six >=1.10.0
    - protobuf >=3.4.0
    - numpy >=1.12
    - markdown >=2.6.8
    - futures >=3.1.1  # [py27]

test:
  requires:
    - tensorflow-base >=1.9.0,<1.10.0
  imports:
    - tensorboard
  commands:
    # sets an exit value of 1
    # https://github.com/tensorflow/tensorboard/issues/1007
    - tensorboard --help | grep USAGE  # [unix]

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  license_family: Apache
  summary: TensorBoard lets you watch Tensors Flow
  dev_url: https://github.com/tensorflow/tensorboard
